name: Generate tree.json

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Clone target repo
        run: |
          git clone --depth=1 https://github.com/menju2ikg8uti/code.git repo

      - name: Generate tree.json
        run: |
          REPO="menju2ikg8uti/code"
          BRANCH="main"

          echo "[" > tree.json
          cd repo

          # FOLDER
          find . -type d \
            ! -path "./.git*" \
            | sed 's|^./||' \
            | grep -v '^$' \
            | while read dir; do
                echo "  {\"type\":\"dir\",\"path\":\"$dir\"}," >> ../tree.json
              done

          # FILE
          find . -type f \
            ! -path "./.git/*" \
            | sed 's|^./||' \
            | while read file; do
                echo "  {\"type\":\"file\",\"path\":\"$file\",\"raw\":\"https://raw.githubusercontent.com/$REPO/$BRANCH/$file\"}," >> ../tree.json
              done

          cd ..
          sed -i '$ s/,$//' tree.json
          echo "]" >> tree.json

      - name: Commit tree.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add tree.json
          git commit -m "data: cycle finished"
          git push pages
